export const diseases = [
  { id: "disease1", name: "Acne" },
  { id: "disease2", name: "Asthma" },
  { id: "disease3", name: "AIDS" },
  { id: "disease4", name: "Alzheimer’s Disease" },
  { id: "disease5", name: "Angina Pectoris" },
  { id: "disease6", name: "Anemia" },
  { id: "disease7", name: "Arthritis" },
  { id: "disease8", name: "Astigmatism" },
  { id: "disease9", name: "Atherosclerosis" },
  { id: "disease10", name: "Autism Spectrum Disorder" },
  { id: "disease11", name: "Bacterial Vaginosis" },
  { id: "disease12", name: "Bronchitis" },
  { id: "disease13", name: "Bubonic Plague" },
  { id: "disease14", name: "Celiac Disease" },
  { id: "disease15", name: "Chickenpox" },
  { id: "disease16", name: "Cholera" },
  { id: "disease17", name: "Chronic Fatigue Syndrome" },
  { id: "disease18", name: "Cirrhosis" },
  { id: "disease19", name: "Cystic Fibrosis" },
  { id: "disease20", name: "Dengue Fever" },
  { id: "disease21", name: "Diabetes Mellitus" },
  { id: "disease22", name: "Diphtheria" },
  { id: "disease23", name: "Down Syndrome" },
  { id: "disease24", name: "Epilepsy" },
  { id: "disease25", name: "Eczema" },
  { id: "disease26", name: "Emphysema" },
  { id: "disease27", name: "Encephalitis" },
  { id: "disease28", name: "Endometriosis" },
  { id: "disease29", name: "Epstein-Barr Virus" },
  { id: "disease30", name: "Gastroenteritis" },
  { id: "disease31", name: "Glaucoma" },
  { id: "disease32", name: "Gout" },
  { id: "disease33", name: "Guillain-Barré Syndrome" },
  { id: "disease34", name: "Hepatitis A" },
  { id: "disease35", name: "Hepatitis B" },
  { id: "disease36", name: "Hepatitis C" },
  { id: "disease37", name: "Herpes Simplex Virus" },
  { id: "disease38", name: "HIV/AIDS" },
  { id: "disease39", name: "Hypertension" },
  { id: "disease40", name: "Hyperthyroidism" },
  { id: "disease41", name: "Hypothyroidism" },
  { id: "disease42", name: "Influenza" },
  { id: "disease43", name: "Irritable Bowel Syndrome" },
  { id: "disease44", name: "Kidney Stones" },
  { id: "disease45", name: "Lung Cancer" },
  { id: "disease46", name: "Lyme Disease" },
  { id: "disease47", name: "Malaria" },
  { id: "disease48", name: "Measles" },
  { id: "disease49", name: "Multiple Sclerosis" },
  { id: "disease50", name: "Muscular Dystrophy" },
  { id: "disease51", name: "Mumps" },
  { id: "disease52", name: "Myocardial Infarction" },
  { id: "disease53", name: "Osteoarthritis" },
  { id: "disease54", name: "Osteoporosis" },
  { id: "disease55", name: "Parkinson’s Disease" },
  { id: "disease56", name: "Peptic Ulcer Disease" },
  { id: "disease57", name: "Pneumonia" },
  { id: "disease58", name: "Polio" },
  { id: "disease59", name: "Psoriasis" },
  { id: "disease60", name: "Rabies" },
  { id: "disease61", name: "Rheumatic Fever" },
  { id: "disease62", name: "Rheumatoid Arthritis" },
  { id: "disease63", name: "Rotavirus Infection" },
  { id: "disease64", name: "Rubella" },
  { id: "disease65", name: "Scarlet Fever" },
  { id: "disease66", name: "Sickle Cell Anemia" },
  { id: "disease67", name: "Sleep Apnea" },
  { id: "disease68", name: "Smallpox" },
  { id: "disease69", name: "Stroke" },
  { id: "disease70", name: "Syphilis" },
  { id: "disease71", name: "Tetanus" },
  { id: "disease72", name: "Tuberculosis" },
  { id: "disease73", name: "Typhoid Fever" },
  { id: "disease74", name: "Ulcerative Colitis" },
  { id: "disease75", name: "Urinary Tract Infection" },
  { id: "disease76", name: "Varicella" },
  { id: "disease77", name: "Viral Meningitis" },
  { id: "disease78", name: "Vitamin D Deficiency" },
  { id: "disease79", name: "Warts" },
  { id: "disease80", name: "West Nile Virus" },
  { id: "disease81", name: "Whooping Cough" },
  { id: "disease82", name: "Wilson’s Disease" },
  { id: "disease83", name: "Zika Virus" },
  { id: "disease84", name: "Cervical Cancer" },
  { id: "disease85", name: "Colorectal Cancer" },
  { id: "disease86", name: "Esophageal Cancer" },
  { id: "disease87", name: "Liver Cancer" },
  { id: "disease88", name: "Pancreatic Cancer" },
  { id: "disease89", name: "Prostate Cancer" },
  { id: "disease90", name: "Skin Cancer" },
  { id: "disease91", name: "Stomach Cancer" },
  { id: "disease92", name: "Thyroid Cancer" },
  { id: "disease93", name: "Endometrial Cancer" },
  { id: "disease94", name: "Bipolar Disorder" },
  { id: "disease95", name: "Depression" },
  { id: "disease96", name: "Generalized Anxiety Disorder" },
  { id: "disease97", name: "Panic Disorder" },
  { id: "disease98", name: "Schizophrenia" },
  { id: "disease99", name: "Obsessive Compulsive Disorder" },
  { id: "disease100", name: "Post-Traumatic Stress Disorder" },
];


export const allergies = [
  { id: "1", name: "Pollen" },
  { id: "2", name: "Dust Mites" },
  { id: "3", name: "Animal Dander" },
  { id: "4", name: "Mold" },
  { id: "5", name: "Food Allergies" },
  { id: "6", name: "Bee Stings" },
  { id: "7", name: "Latex" },
  { id: "8", name: "Insect Bites" },
  { id: "9", name: "Medication Allergies" },
  { id: "10", name: "Shellfish" },
  { id: "11", name: "Peanuts" },
  { id: "12", name: "Wheat" },
  { id: "13", name: "Eggs" },
  { id: "14", name: "Milk" },
  { id: "15", name: "Soy" },
  { id: "16", name: "Tree Nuts" },
  { id: "17", name: "Fish" },
  { id: "18", name: "Citrus Fruits" },
  { id: "19", name: "Tomatoes" },
  { id: "20", name: "Garlic" },
  { id: "21", name: "Onions" },
  { id: "22", name: "Strawberries" },
  { id: "23", name: "Bananas" },
  { id: "24", name: "Avocados" },
  { id: "25", name: "Berries" },
  { id: "26", name: "Chocolate" },
  { id: "27", name: "Alcohol" },
  { id: "28", name: "Gluten" },
  { id: "29", name: "Corn" },
  { id: "30", name: "Dairy Products" },
  { id: "31", name: "Caffeine" },
  { id: "32", name: "Mustard" },
  { id: "33", name: "Sesame Seeds" },
  { id: "34", name: "Spices" },
  { id: "35", name: "Chicken" },
  { id: "36", name: "Turkey" },
  { id: "37", name: "Beef" },
  { id: "38", name: "Pork" },
  { id: "39", name: "Lamb" },
  { id: "40", name: "Shellfish (Shrimp, Lobster, Crab)" },
  { id: "41", name: "Coconut" },
  { id: "42", name: "Honey" },
  { id: "43", name: "Cheese" },
  { id: "44", name: "Cherries" },
  { id: "45", name: "Peach" },
  { id: "46", name: "Plums" },
  { id: "47", name: "Apricots" },
  { id: "48", name: "Grapes" },
  { id: "49", name: "Raspberries" },
  { id: "50", name: "Papaya" },
  { id: "51", name: "Mango" },
  { id: "52", name: "Olives" },
  { id: "53", name: "Dried Fruits" },
  { id: "54", name: "Chili Peppers" },
  { id: "55", name: "Red Meat" },
  { id: "56", name: "Lettuce" },
  { id: "57", name: "Carrots" },
  { id: "58", name: "Celery" },
  { id: "59", name: "Cucumber" },
  { id: "60", name: "Potatoes" },
  { id: "61", name: "Beans" },
  { id: "62", name: "Lentils" },
  { id: "63", name: "Peas" },
  { id: "64", name: "Chickpeas" },
  { id: "65", name: "Spinach" },
  { id: "66", name: "Cabbage" },
  { id: "67", name: "Eggplant" },
  { id: "68", name: "Kale" },
  { id: "69", name: "Radishes" },
  { id: "70", name: "Squash" },
  { id: "71", name: "Pumpkin" },
  { id: "72", name: "Sweet Potatoes" },
  { id: "73", name: "Zucchini" },
  { id: "74", name: "Broccoli" },
  { id: "75", name: "Cauliflower" },
  { id: "76", name: "Asparagus" },
  { id: "77", name: "Seaweed" },
  { id: "78", name: "Caviar" },
  { id: "79", name: "Almonds" },
  { id: "80", name: "Cashews" },
  { id: "81", name: "Hazelnuts" },
  { id: "82", name: "Macadamia Nuts" },
  { id: "83", name: "Pistachios" },
  { id: "84", name: "Walnuts" },
  { id: "85", name: "Brazil Nuts" },
  { id: "86", name: "Chia Seeds" },
  { id: "87", name: "Flax Seeds" },
  { id: "88", name: "Sunflower Seeds" },
  { id: "89", name: "Pumpkin Seeds" },
  { id: "90", name: "Lemon" },
  { id: "91", name: "Lime" },
  { id: "92", name: "Orange" },
  { id: "93", name: "Grapefruit" },
  { id: "94", name: "Blueberries" },
  { id: "95", name: "Kiwi" },
  { id: "96", name: "Apples" },
  { id: "97", name: "Pears" },
  { id: "98", name: "Plums" },
  { id: "99", name: "Figs" },
  { id: "100", name: "Apricots" },
];
